### ISSUE TITLE
Is the bot functional?

### ISSUE THREAD

**Issue by Sphynxcatkillstreak** [Steam-Chat-Bot/SteamChatBot#1]
Is the bot already functional? I'm getting the same error message that is also shown on [this](https://raw.githubusercontent.com/Steam-Chat-Bot/SteamChatBot/master/Screenshots/logger.png) screenshot.

**Comment by kjsmita6** [comment]
That just means it can't connect to steam, after a while it should connect.

**Comment by Sphynxcatkillstreak** [comment]
Worked! Thank you!
