### ISSUE TITLE
Ban trigger not working 

### ISSUE THREAD

**Issue by ghost** [Steam-Chat-Bot/SteamChatBot#3]
Hey, so the ban trigger is no longer working not sure if it could be problem with Steam or something else but I add the command as !ban, invite the bot in a group chat and type !ban (steam3ID) and nothing happens. Any ideas what could be wrong?

**Comment by kjsmita6** [comment]
I belive you must do it as a steamid64. I may add something in the future
which will automatically convert it to the correct format.

Steamid64: 76561198091343023

**Comment by ghost** [comment]
Thanks it worked! But it was working with steam3ID and steamID32 and now the only one that works is SteamID64
