### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by MasonR112** [Steam-Chat-Bot/SteamChatBot#4]
I really dont get how to install this. Can someone help

**Comment by kjsmita6** [comment]
In the [releases](https://github.com/Steam-Chat-Bot/SteamChatBot/releases)
section of this repository, download the msi installer file. Run it follow
the installation process. Once it is done it will be installed in the
directory of your choice. Create a shortcut on your desktop and run it.

When you run it a notification will show up saying that Windows smartscreen
protected your pc. This is because I didn't sign the application. Press
"more info" and then "run anyways".

**Comment by MasonR112** [comment]
Right, i have done this, i have opened the steam bot and when i setup the triggers and put my username and password for steam: https://gyazo.com/e06c75ce0edf79288e5ee845f59f4f54 , then i will start bot and it doesnt do anything it will do this: https://gyazo.com/0a4df0250d5195a1e469967bd0d99a6e

**Comment by kjsmita6** [comment]
It just needs time to connect. Be patient and eventually it will connect
and log in.

**Comment by MasonR112** [comment]
https://gyazo.com/010dde1a9373a0f71f7f58e4d1c2ec51

**Comment by MasonR112** [comment]
It constantly does that, i left it for 5 minutes

**Comment by MasonR112** [comment]
https://gyazo.com/9d5946ff8b8ab4071a44090fbdfb93fb that came up, there is no "login.json"

**Comment by kjsmita6** [comment]
When it logs in there is a pop up window that asks to save to login.json. Did you see that?

I don't have access to a computer right now so I can't do much but I'll fix the connecting taking so long when I get back.

**Comment by MasonR112** [comment]
No that didnt show up

**Comment by kjsmita6** [comment]
Is this still a problem for you or has it been resolved?

**Comment by MasonR112** [comment]
Still an issue

**Comment by kjsmita6** [comment]
There have been a lot of updates. Try instaaling the newest version ans try again.

**Comment by MasonR112** [comment]
I reinstall it and this happens: https://gyazo.com/24a33c8e311edf8e03c2b36fb28ec4ca

**Comment by MasonR112** [comment]
It does keep sending notifications to my phone to login though, steam codes for mobile authenticator

**Comment by kjsmita6** [comment]
I fixed the issue in [this release](https://github.com/Steam-Chat-Bot/SteamChatBot/releases/tag/0.3.5) after testing it on my own account. I was getting the same problem that you were and I fixed it. Sorry for the inconvenience!
