### ISSUE TITLE
Auto message for bot

### ISSUE THREAD

**Issue by woodiertexas** [Steam-Chat-Bot/SteamChatBot#7]
- ~~Auto message trigger (like Efreak's)~~ 0.6.0
- ~~!google~~ 0.6.0
- ~~!youtube~~ 0.6.0
- ~~!8ball~~ (ChatReplyTrigger)
- ~~Editing triggers from GUI~~ Maybe future update
- ~~Add "filter delete" to NotificationTrigger to only delete one item~~ 0.6.0
- ~~!name to change bots name (in login.json too)~~ 0.6.0

**Comment by modbotmaker** [comment]
Here is a list of stuff to add to the GUI:

- a !google trigger

- a !youtube trigger

- an !8ball trigger

- the ability to edit triggers from the GUI so i don't have to exit the GUI and delete trigger X and make it all over again.
